### PR TITLE
Fix for gvcf chunk size, as well as an addition of the ability to use minimal gvcf chunking

### PR DESCRIPTION
**Pull request by Nheyer**
see Title

### CODE REVIEW

**Comment by Nheyer** [comment]
failed check is  
"not ok 20 - freebayes produces the expected number of lines of gVCF output
#          got: '250'
#     expected: '245'
"
but makes sense as the size of chunks was edited, to fix the noninclusive bug 
spelling has also been fixed

**Comment by ekg** [comment]
If you inspect this and see it matches your expectations about the gVCF
output, then please push a fix to the test to match the new behavior.

**Comment by Nheyer** [comment]
done, and pushed, also fixed an assert to be more informative about why it breaks ...

**Comment by Nheyer** [comment]
should close this as well
#241

**Pull request merged**
