### PR TITLE
Improve handling of complex alleles

### PR DESCRIPTION
**Pull request by ekg**
The complexity of the allele parsing algorithm that converted a read into a series of alleles made it easy for us to introduce a number of bugs, the ultimate result of which was an elimination of certain kinds of complex alleles. These commits rewrite the allele parsing logic to be simpler and easier to maintain, and resolve the underlying problem. They also resolve a number of other minor issues, such as a problem with reported depth in some contexts.

### CODE REVIEW

**Comment by ekg** [comment]
CC @chapmanb @mlin : This commit could use some third-party automated testing. As far as I can tell from my testing this is only improving things. However, I haven't scaled the tests up and if either of you have a push-button way to do so that'd be very helpful.

**Comment by chapmanb** [comment]
Erik -- I'd be happy to test this. Would it be possible to synchronize with @walaj and get the latest version of SeqLib included in the main branch? I believe this would take an update of #338 to fix conflicts. This would be very helpful for builds since the recent SeqLib uses htslib 1.5, which would synchronize us with samtools and bcftools requirements. That SeqLib improvement/update PR has been languishing for a while but is really useful so would be great to get in.

**Comment by chapmanb** [comment]
Erik -- thanks for the SeqLib merge and update. This now builds cleanly with htslib 1.5 and I'll do some validation runs. Much appreciated.

**Comment by chapmanb** [comment]
Erik -- thanks again for all the fixes and updates. The latest HEAD is running great and validations look good compared to the previous versions:

https://github.com/bcbio/bcbio_validations/tree/master/freebayes#11044

Thanks for the code cleanup and improvements. I'll build a new bioconda package to make this version available and we'll switch over to using it in bcbio. Thanks again.

**Pull request merged**
