### PR TITLE
Fix freebayes-parallel word splitting

### PR DESCRIPTION
**Pull request by mckinsel**
`freebayes-parallel` splits all of its arguments on spaces, but this isn't really what you want if you're passing it, say, a quoted file name with spaces. These changes make sure that variables are appropriately quoted.

There's also a couple new tests for freebayes-parallel in here, though these require building vcflib.

### CODE REVIEW

**Comment by mlin** [comment]
@mckinsel would you rebase this on master whenever you get a chance?

**Comment by mckinsel** [comment]
@mlin, it's rebased now. I also squashed it to one commit.

**Comment by ekg** [comment]
I'm still having some issues with this:

```tap

could not open tiny/q
could not open tiny/q
could not open tiny/q
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
../scripts/freebayes-parallel: line 40: 13158 Exit 3                  ( cat "$regionsfile" | parallel -k -j "$ncpus" "${command[@]}" --region {} )
     13159 Done                    | vcffirstheader
     13160 Aborted                 (core dumped) | vcfstreamsort -w 1000
     13162 Aborted                 (core dumped) | vcfuniq
not ok 17 - freebayes handles spaces in file names

```

**Comment by bgruening** [comment]
@ekg as a general question the splitter does not have overlapping windows. So if you have an indel crossing the two window borders it will not be called, isn't it?

**Comment by ekg** [comment]
The default splitter does not have overlapping windows.

A basic solution would be to overlap them and change the merge strategy.

**Comment by bgruening** [comment]
This is what I was trying here: https://github.com/galaxyproject/tools-devteam/pull/265
Maybe freebayes should offer something similar as default as part of the splitter to not create wrong results.

**Comment by ekg** [comment]
Agreed. It should do this parallelization transparently and merge the
results. That's on the to do list. After gVCF.

**Comment by mlin** [comment]
+Marcus






On Fri, Nov 13, 2015 at 7:47 AM -0800, "Erik Garrison" <notifications@github.com> wrote:
I'm still having some issues with this:

```tap

could not open tiny/q
could not open tiny/q
could not open tiny/q
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
../scripts/freebayes-parallel: line 40: 13158 Exit 3                  ( cat "$regionsfile" | parallel -k -j "$ncpus" "${command[@]}" --region {} )
     13159 Done                    | vcffirstheader
     13160 Aborted                 (core dumped) | vcfstreamsort -w 1000
     13162 Aborted                 (core dumped) | vcfuniq
not ok 17 - freebayes handles spaces in file names

```

---

**Pull request merged**
