### PR TITLE
Allow compilation of bamtools with nodejs support

### PR DESCRIPTION
**Pull request by aacn500**
Possible fix to #313

### CODE REVIEW

**Comment by ekg** [comment]
We are looking to move to SeqLib. This feature is one thing we would lose.
Could we port the functionality to SeqLib? How are you using this
functionality?

**Comment by aacn500** [comment]
Hi,
I just quickly tried the SeqLib pr, as far as I can tell it works out of the box for our usage.
This pull request was just to dodge an issue caused by freopen [here](https://github.com/ekg/bamtools/blob/e77a43f5097ea7eee432ee765049c6b246d49baa/src/api/internal/io/BamPipe_p.cpp#L31), rather than enable any extra functionality.
I'll keep trying with the SeqLib version and let you know if we have any issues.

**Comment by ekg** [comment]
Great to hear this works out for you! I expect we will pull it in to master
soon.

**Comment by aacn500** [comment]
With the 1.1.0 release, this is now no longer needed.
Thanks!

**Pull request closed without merging**
