### PR TITLE
Writing out FORMAT/DPR tag in addition to FORMAT/DP and FORMAT/AO

### PR DESCRIPTION
**Pull request by holtgrewe**
This makes the output more similar to bcftools call.

### CODE REVIEW

**Comment by mcshane** [comment]
DPR is deprecated in samtools/bcftools in favour of the AD,ADF,ADR tags that were introduced into the 4.3 spec. See samtools/hts-specs#78

**Comment by holtgrewe** [comment]
I agree.

**Comment by ekg** [comment]
@holtgrewe would you like me to merge this anyway?

**Comment by holtgrewe** [comment]
It would help me ;)

**Comment by ekg** [comment]
Then done. 4.3 is a topic for another day.

**Pull request merged**
