### PR TITLE
Grch38 hla support

### PR DESCRIPTION
**Pull request by bwlang**
This fixes a problem with : in contig names (as found in grch38's HLA entries)
Also updates test suite with an example.

### CODE REVIEW

**Comment by bwlang** [comment]
ack... look like this is the same fix as 
#274 
leaving it open since that one is out of date and does not have tests

**Comment by bwlang** [comment]
fixes #384

**Comment by ekg** [comment]
I think this makes sense to merge, sorry that it's been dropped.

**Comment by bwlang** [comment]
Thanks - and thanks for your efforts on freebayes.

**Pull request merged**
